"use client";

import { useEffect, useMemo, useState } from "react";

import { ChainBuilder } from "~/components/chain-builder";
import { ConstraintList } from "~/components/constraint-list";
import { ResultPanel } from "~/components/result-panel";
import { UploadPanel } from "~/components/upload-panel";
import type { SolveResult, ValidationResult } from "~/server/puzzle";
import { api } from "~/trpc/react";

type UploadResponse = {
	imageUrl: string;
	error?: string;
};

export function DateAnythingApp() {
	const utils = api.useUtils();
	const [selectedFile, setSelectedFile] = useState<File | null>(null);
	const [previewUrl, setPreviewUrl] = useState<string | null>(null);
	const [errorMessage, setErrorMessage] = useState<string | null>(null);
	const [puzzleId, setPuzzleId] = useState<string | null>(null);
	const [chain, setChain] = useState<string[]>([]);
	const [validation, setValidation] = useState<ValidationResult | null>(null);
	const [solveResult, setSolveResult] = useState<
		(SolveResult & { summary: string; hasSolution: boolean }) | null
	>(null);
	const [isSolving, setIsSolving] = useState(false);

	const generateMutation = api.puzzle.generatePuzzleFromImage.useMutation();
	const validateMutation = api.puzzle.validateChain.useMutation();
	const puzzleQuery = api.puzzle.getPuzzle.useQuery(
		{ puzzleId: puzzleId ?? "" },
		{ enabled: Boolean(puzzleId) },
	);

	const providerMeta = generateMutation.data?.providerMeta;
	const puzzle = puzzleQuery.data?.puzzle;

	useEffect(() => {
		if (!selectedFile) {
			setPreviewUrl(null);
			return;
		}
		const objectUrl = URL.createObjectURL(selectedFile);
		setPreviewUrl(objectUrl);
		return () => {
			URL.revokeObjectURL(objectUrl);
		};
	}, [selectedFile]);

	const uploadImage = async (file: File): Promise<string> => {
		const formData = new FormData();
		formData.set("file", file);

		const response = await fetch("/api/upload", {
			method: "POST",
			body: formData,
		});
		const payload = (await response.json()) as UploadResponse;
		if (!response.ok || !payload.imageUrl) {
			throw new Error(payload.error ?? "Upload failed.");
		}
		return payload.imageUrl;
	};

	const handleGenerate = async () => {
		if (!selectedFile) {
			setErrorMessage("Choose an image first.");
			return;
		}

		try {
			setErrorMessage(null);
			setValidation(null);
			setSolveResult(null);
			setChain([]);

			const imageUrl = await uploadImage(selectedFile);
			const generated = await generateMutation.mutateAsync({ imageUrl });
			setPuzzleId(generated.puzzleId);
			await utils.puzzle.getPuzzle.invalidate();
		} catch (error) {
			setErrorMessage(
				error instanceof Error ? error.message : "Generation failed.",
			);
		}
	};

	const handleAddCard = (cardId: string) => {
		if (!puzzle) return;
		if (chain.length >= puzzle.chainLength) return;
		if (!puzzle.allowRepeatedCards && chain.includes(cardId)) return;
		setChain((prev) => [...prev, cardId]);
	};

	const handleRemoveCard = (index: number) => {
		setChain((prev) => prev.filter((_, idx) => idx !== index));
	};

	const handleMoveLeft = (index: number) => {
		if (index === 0) return;
		setChain((prev) => {
			const next = [...prev];
			const left = next[index - 1];
			const right = next[index];
			if (!left || !right) return prev;
			next[index - 1] = right;
			next[index] = left;
			return next;
		});
	};

	const handleMoveRight = (index: number) => {
		setChain((prev) => {
			if (index >= prev.length - 1) return prev;
			const next = [...prev];
			const left = next[index];
			const right = next[index + 1];
			if (!left || !right) return prev;
			next[index] = right;
			next[index + 1] = left;
			return next;
		});
	};

	const handleReset = () => {
		setChain([]);
		setValidation(null);
		setSolveResult(null);
	};

	const handleValidate = async () => {
		if (!puzzleId) return;
		const result = await validateMutation.mutateAsync({ puzzleId, chain });
		setValidation(result);
	};

	const handleSolve = async () => {
		if (!puzzleId) return;
		setIsSolving(true);
		try {
			const result = await utils.puzzle.solvePuzzle.fetch({
				puzzleId,
				includeAllValidSolutions: true,
			});
			setSolveResult(result);
		} finally {
			setIsSolving(false);
		}
	};

	const providerMessage = useMemo(() => {
		if (!providerMeta) return null;
		if (providerMeta.usedFallback) {
			const detail = providerMeta.errorMessage?.trim();
			return detail
				? `Fallback puzzle mode active. Reason: ${detail}`
				: "Fallback puzzle mode active (missing key or parsing error). Deterministic engine is still fully active.";
		}
		return `Generated by ${providerMeta.provider} (${providerMeta.model}).`;
	}, [providerMeta]);

	return (
		<main className="relative min-h-screen overflow-hidden bg-[radial-gradient(circle_at_20%_0%,#334155_0%,#0f172a_55%,#020617_100%)] px-4 py-8 text-slate-50">
			<div className="pointer-events-none absolute inset-0 bg-[linear-gradient(120deg,rgba(251,191,36,0.08),transparent_35%),linear-gradient(240deg,rgba(56,189,248,0.08),transparent_40%)]" />
			<div className="relative mx-auto flex w-full max-w-7xl flex-col gap-6">
				<header className="rounded-3xl border border-white/20 bg-black/30 p-6 backdrop-blur-sm">
					<p className="font-semibold text-amber-300 text-xs uppercase tracking-[0.2em]">
						LLM + Classical AI Constraint Solver
					</p>
					<h1 className="mt-2 font-bold text-4xl text-white md:text-5xl">
						Date Aiverything
					</h1>
					<p className="mt-3 max-w-4xl text-slate-200">
						Upload a photo of any object. The model roleplays as your weird new
						crush and emits a strict puzzle JSON. Then a deterministic recursive
						backtracking solver validates and optimizes your conversation chain.
					</p>
					{providerMessage ? (
						<p className="mt-4 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-slate-200 text-sm">
							{providerMessage}
						</p>
					) : null}
				</header>

				<div className="grid gap-6 lg:grid-cols-[1.15fr_1.6fr_1.25fr]">
					<UploadPanel
						errorMessage={errorMessage}
						hasFile={Boolean(selectedFile)}
						isGenerating={generateMutation.isPending}
						onFileChange={setSelectedFile}
						onGenerate={handleGenerate}
						previewUrl={previewUrl}
					/>

					<div className="space-y-4">
						{puzzle ? (
							<>
								<section className="rounded-3xl border border-white/15 bg-black/30 p-5">
									<h2 className="font-semibold text-white text-xl">
										2) Meet Your Object
									</h2>
									<p className="mt-2 text-slate-300 text-sm">
										{puzzle.objectName}
									</p>
									<p className="mt-1 text-amber-200 text-sm">
										{puzzle.objectPersona}
									</p>
									<p className="mt-3 rounded-xl border border-amber-300/25 bg-amber-400/10 p-3 text-slate-100 text-sm">
										{puzzle.introText}
									</p>
								</section>
								<ConstraintList constraints={puzzle.constraints} />
								<ChainBuilder
									chain={chain}
									isSolving={isSolving}
									isValidating={validateMutation.isPending}
									onAddCard={handleAddCard}
									onMoveLeft={handleMoveLeft}
									onMoveRight={handleMoveRight}
									onRemoveCard={handleRemoveCard}
									onReset={handleReset}
									onSolve={handleSolve}
									onValidate={handleValidate}
									puzzle={puzzle}
								/>
							</>
						) : (
							<section className="rounded-3xl border border-white/20 border-dashed bg-black/20 p-8 text-slate-300 text-sm">
								Generate a puzzle to unlock persona text, card deck,
								constraints, and solver actions.
							</section>
						)}
					</div>

					<ResultPanel solveResult={solveResult} validation={validation} />
				</div>
			</div>
		</main>
	);
}
